# Google App Engine Configuration for LaborLooker - OPTIMIZED FOR GOOGLE CLOUD & MOBILE
runtime: python311

# Instance class optimized for performance and scalability
instance_class: F4_1G

# Automatic scaling configuration for high availability
automatic_scaling:
  min_instances: 1
  max_instances: 20
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.8

# Environment variables for production with performance optimizations
env_variables:
  # Performance optimizations
  PYTHONUNBUFFERED: "1"
  FLASK_SKIP_DOTENV: "1"
  
  # Application configuration
  SECRET_KEY: "57c4add28c3622f4d4ba3c82b2fe06032e99b715fcfb00f0e6f45f221c99606d"
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"
  
  # Mail configuration
  MAIL_USERNAME: "taschris.executive@gmail.com"
  MAIL_PASSWORD: "jekqe6-ceqkuv-seZbyg"
  
  # PayPal configuration
  PAYPAL_CLIENT_ID: "AWC4ekd4ChKsiY97ieWyVxAk2QKjMHAGblhTUlGTOtdWRrVtoninTD5v9CKi7G_e3pPpxCZdPp2C9d1i"
  PAYPAL_CLIENT_SECRET: "EG6BFP37JcCZPyq2q2NBsJWwWhUMUTRiiQ2I8FQCI6TK_5zuOuKeRUkUDvZIWCT1723K--xAlcTTRvAI"
  PAYPAL_MODE: "live"
  
  # Mobile app and API configuration
  MOBILE_API_ENABLED: "true"
  API_VERSION: "v1"
  CORS_ORIGINS: "https://laborlooker.com,https://www.laborlooker.com,https://api.laborlooker.com,capacitor://localhost,ionic://localhost"
  
  # Performance and caching
  CACHE_TYPE: "redis"
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_DEFAULT: "100 per hour"
  RATE_LIMIT_API: "200 per hour"
  CDN_ENABLED: "true"
  CDN_CACHE_TIMEOUT: "3600"
  
  # Security settings
  BCRYPT_LOG_ROUNDS: "12"
  JWT_ACCESS_TOKEN_EXPIRES: "3600"
  SESSION_TIMEOUT: "1800"
  # Using SQLite for simplicity - production ready
  DATABASE_URL: "sqlite:///laborlooker.db"
  # Gateway stability configurations
  GAE_ENV: "standard"
  GOOGLE_CLOUD_PROJECT: "laborlooker-2024-476019"
  # Performance monitoring
  FLASK_PERFORMANCE_MONITORING: "1"
  REQUEST_TIMEOUT: "60"

# Static file handlers
handlers:
- url: /_ah/health
  script: main.app
  secure: always
  
- url: /_ah/start  
  script: main.app
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: main.app
  secure: always

# Auto-scaling configuration for high performance (25% PC power equivalent)
automatic_scaling:
  min_instances: 3
  max_instances: 50
  min_idle_instances: 3
  max_idle_instances: 10
  target_cpu_utilization: 0.5
  target_throughput_utilization: 0.6

# Enhanced resources for 25% PC computing power equivalent
resources:
  cpu: 4
  memory_gb: 2.3
  disk_size_gb: 50

# Health check configuration to prevent gateway issues
readiness_check:
  path: "/_ah/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/_ah/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2