packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/node': ^20.11.16
  typescript: ^5.3.3
  zod: ^3.22.4
  prisma: ^5.9.1
  '@prisma/client': ^5.9.1
  '@nestjs/core': ^10.3.2
  '@nestjs/common': ^10.3.2
  next: ^14.1.0
  react: ^18.2.0
  socket.io: ^4.7.4
  bullmq: ^5.1.1
  ioredis: ^5.3.2